apiVersion: v1
kind: ConfigMap
metadata:
  name: admission-config
  namespace: production
data:
  APP_ENV: production
  UPLOAD_FOLDER: /app/uploads
  POSTGRES_DB: admission
  POSTGRES_USER: admission
